import { BudgetLevel, type FoodItem } from './menuTypes';

export const HARDEN_QUOTES = [
  "后撤步是我的生活态度，但这道菜让我不想后退。",
  "我是基石，不仅是球队的，也是菜单的。",
  "有时候你需要慢下来，才能看清那个空位（或者那道菜）。",
  "这不是犯规，这是艺术。",
  "欧洲步过掉你的饥饿感。",
  "只有吃饱了，胡子才能长得更好。",
  "这菜单比我的技能包还要丰富。"
];

export const NORTHERN_FOOD_MENU: FoodItem[] = [
  // --- 经典北方 ---
  {
    id: '1',
    name: '煎饼果子 (加十个蛋)',
    price: 25,
    budget: BudgetLevel.VALUE,
    emoji: '🥞',
    description: '来自东方的神秘力量，比我的胡子还蓬松。'
  },
  {
    id: '2',
    name: '咸豆腐脑 (甜党异端)',
    price: 5,
    budget: BudgetLevel.POOR,
    emoji: '🥣',
    description: '只有咸的才是正义，就像我的罚球一样稳。'
  },
  {
    id: '3',
    name: '烤冷面 (尊享版)',
    price: 18,
    budget: BudgetLevel.VALUE,
    emoji: '🍜',
    description: 'Q弹劲道，像极了我在内线的欧洲步。'
  },
  {
    id: '4',
    name: '全聚德烤鸭 (MVP独享)',
    price: 298,
    budget: BudgetLevel.RICH,
    emoji: '🦆',
    description: '奢华的口感，就像拿了MVP之后的庆功宴。'
  },
  {
    id: '5',
    name: '老北京炸酱面',
    price: 22,
    budget: BudgetLevel.VALUE,
    emoji: '🍝',
    description: '地道的老味道，拌开的一瞬间就是助攻的快感。'
  },
  // --- 西北硬汉 ---
  {
    id: '6',
    name: '羊肉泡馍 (自己掰)',
    price: 38,
    budget: BudgetLevel.VALUE,
    emoji: '🍲',
    description: '掰馍的时间比罚球准备动作还长，但这汤头值得等待。'
  },
  {
    id: '7',
    name: '兰州牛肉面 (一清二白)',
    price: 15,
    budget: BudgetLevel.POOR,
    emoji: '🍜',
    description: '拉面师傅的手速比我的运球还快，辣油是绝杀。'
  },
  {
    id: '8',
    name: '肉夹馍 (纯瘦)',
    price: 12,
    budget: BudgetLevel.POOR,
    emoji: '🍔',
    description: '中国的汉堡，肉给的实在，就像我的造犯规一样稳。'
  },
  {
    id: '9',
    name: '大盘鸡 (加宽面)',
    price: 88,
    budget: BudgetLevel.RICH,
    emoji: '🐔',
    description: '分量大得惊人，就像我在火箭队时的球权占有率。'
  },
  {
    id: '10',
    name: '新疆羊肉串 (10串)',
    price: 60,
    budget: BudgetLevel.VALUE,
    emoji: '🍢',
    description: '撸串是男人的浪漫，稍微带点肥油才香。'
  },
  // --- 川渝火辣 ---
  {
    id: '11',
    name: '四川火锅 (九宫格)',
    price: 128,
    budget: BudgetLevel.RICH,
    emoji: '🥘',
    description: '防守强度很大，辣得你根本突不进去。'
  },
  {
    id: '12',
    name: '麻婆豆腐',
    price: 18,
    budget: BudgetLevel.POOR,
    emoji: '🍛',
    description: '麻辣鲜香，口感比我的控球还要丝滑。'
  },
  {
    id: '13',
    name: '重庆小面',
    price: 10,
    budget: BudgetLevel.POOR,
    emoji: '🍜',
    description: '早餐吃这个，一整天都像打了鸡血一样兴奋。'
  },
  // --- 粤式精致 ---
  {
    id: '14',
    name: '广东早茶 (一盅两件)',
    price: 88,
    budget: BudgetLevel.RICH,
    emoji: '🥟',
    description: '细腻的技术流，讲究的就是一个战术配合。'
  },
  {
    id: '15',
    name: '干炒牛河',
    price: 28,
    budget: BudgetLevel.VALUE,
    emoji: '🥡',
    description: '必须要有镬气，就像比赛必须要有火药味。'
  },
  {
    id: '16',
    name: '煲仔饭 (双拼)',
    price: 35,
    budget: BudgetLevel.VALUE,
    emoji: '🍲',
    description: '底下的锅巴是精华，就像最后时刻的绝杀球。'
  },
  // --- 华东鲜甜 ---
  {
    id: '17',
    name: '上海小笼包',
    price: 20,
    budget: BudgetLevel.VALUE,
    emoji: '🥟',
    description: '皮薄馅大，小心烫嘴，比防守陷阱还危险。'
  },
  {
    id: '18',
    name: '西湖醋鱼',
    price: 168,
    budget: BudgetLevel.RICH,
    emoji: '🐟',
    description: '这酸爽，就像输了球之后看录像一样难受又上头。'
  },
  {
    id: '19',
    name: '红烧肉 (本帮菜)',
    price: 58,
    budget: BudgetLevel.VALUE,
    emoji: '🥓',
    description: '浓油赤酱，肥而不腻，就像我有肉但很灵活。'
  },
  // --- 湘鄂重口 ---
  {
    id: '20',
    name: '长沙臭豆腐',
    price: 10,
    budget: BudgetLevel.POOR,
    emoji: '⬛',
    description: '闻着臭吃着香，就像我的打法，有人黑但就是能赢。'
  },
  {
    id: '21',
    name: '武汉热干面',
    price: 6,
    budget: BudgetLevel.POOR,
    emoji: '🍜',
    description: '芝麻酱拌匀，干干的口感，像极了没有空调的球馆。'
  },
  {
    id: '22',
    name: '剁椒鱼头',
    price: 68,
    budget: BudgetLevel.VALUE,
    emoji: '🌶️',
    description: '红红火火，吃完感觉能立刻上场打满48分钟。'
  },
  // --- 黑暗/特色 ---
  {
    id: '23',
    name: '螺蛳粉 (加臭加辣)',
    price: 18,
    budget: BudgetLevel.VALUE,
    emoji: '🍜',
    description: '这味道能统治整个球场，对手闻风丧胆。'
  },
  {
    id: '24',
    name: '折耳根 (鱼腥草)',
    price: 8,
    budget: BudgetLevel.POOR,
    emoji: '🌿',
    description: '爱的人很爱，恨的人很恨，就像对我的评价一样两极分化。'
  },
  {
    id: '25',
    name: '佛跳墙 (顶配)',
    price: 888,
    budget: BudgetLevel.RICH,
    emoji: '🍲',
    description: '顶薪合同才配吃的菜，全是海参鲍鱼，太奢侈了！'
  },
  // --- 甜点饮料 ---
  {
    id: '26',
    name: '珍珠奶茶 (全糖去冰)',
    price: 18,
    budget: BudgetLevel.POOR,
    emoji: '🧋',
    description: '虽然热量爆炸，但甜度让我心情愉悦，休赛期最爱。'
  },
  {
    id: '27',
    name: '驴打滚',
    price: 12,
    budget: BudgetLevel.POOR,
    emoji: '🍡',
    description: '粘粘糯糯，就像沾在身上的防守人甩都甩不掉。'
  },
  {
    id: '28',
    name: '东北锅包肉 (酸甜口)',
    price: 48,
    budget: BudgetLevel.VALUE,
    emoji: '🥓',
    description: '外酥里嫩，咬一口咔滋脆，这声音比刷网声还悦耳。'
  },
  // ... 前面是你的 1-28 号菜品 ...
  {
    id: '29',
    name: '锅包肉 (东北MVP)',
    price: 48,
    budget: BudgetLevel.RICH,
    emoji: '🥩',
    description: '酸甜酥脆，就像哈登的后撤步一样让人防不胜防，绝对的硬菜MVP。',
  },
  {
    id: '30',
    name: '地三鲜 (平民三巨头)',
    price: 22,
    budget: BudgetLevel.VALUE,
    emoji: '🥔',
    description: '茄子土豆青椒的完美配合，不需要巨星也能打出完美的团队篮球。',
  },
  {
    id: '31',
    name: '猪肉炖粉条 (内线大闸)',
    price: 32,
    budget: BudgetLevel.VALUE,
    emoji: '🍲',
    description: '吸满汤汁的粉条，像内线大闸一样扎实，吃完这一顿，这把稳了。',
  },
  {
    id: '32',
    name: '溜肉段 (老派技术流)',
    price: 38,
    budget: BudgetLevel.VALUE,
    emoji: '🍖',
    description: '外酥里嫩，咸鲜口，不搞花里胡哨的酸甜，就是纯粹的技术流。',
  },
  {
    id: '33',
    name: '小鸡炖蘑菇 (全明星首发)',
    price: 58,
    budget: BudgetLevel.RICH,
    emoji: '🍄',
    description: '榛蘑和笨鸡的强强联手，这阵容豪华程度堪比全明星首发。',
  },
  {
    id: '34',
    name: '酸菜白肉 (最佳防守)',
    price: 35,
    budget: BudgetLevel.VALUE,
    emoji: '🥬',
    description: '酸菜解腻，白肉肥美，这道菜的防守（解腻）能力是DPOY级别的。',
  },
  {
    id: '35',
    name: '鱼香肉丝 (国民控卫)',
    price: 24,
    budget: BudgetLevel.VALUE,
    emoji: '🥕',
    description: '虽然没有鱼，但能串联起全场的米饭，绝对的助攻王。',
  },
  {
    id: '36',
    name: '宫保鸡丁 (经典战术)',
    price: 26,
    budget: BudgetLevel.VALUE,
    emoji: '🥜',
    description: '花生米和鸡丁的挡拆配合，教科书般的经典战术，百吃不厌。',
  },
  {
    id: '37',
    name: '尖椒干豆腐 (硬汉联盟)',
    price: 18,
    budget: BudgetLevel.POOR,
    emoji: '🌶️',
    description: '东北爷们的必点菜，简单粗暴，就像强硬的身体对抗。',
  },
  {
    id: '38',
    name: '拔丝地瓜 (甜蜜绝杀)',
    price: 20,
    budget: BudgetLevel.POOR,
    emoji: '🍠',
    description: '趁热吃，拉丝的一瞬间，就像压哨绝杀一样甜蜜又刺激。',
  },
  {
    id: '39',
    name: '酱大骨 (内线肉搏)',
    price: 55,
    budget: BudgetLevel.RICH,
    emoji: '🦴',
    description: '带上手套直接啃，这是属于内线肌肉棒子的肉搏战。',
  },
  {
    id: '40',
    name: '皮蛋瘦肉粥 (轮休养生)',
    price: 12,
    budget: BudgetLevel.POOR,
    emoji: '🥣',
    description: '背靠背比赛累了？来碗粥养生一下，为了季后赛蓄力。',
  },
  {
    id: '41',
    name: '麻婆豆腐 (犯规麻烦)',
    price: 16,
    budget: BudgetLevel.POOR,
    emoji: '🌶️',
    description: '麻辣烫口，吃得太急容易被辣得像陷入犯规麻烦一样下场喝水。',
  },
  {
    id: '42',
    name: '回锅肉 (二阵领袖)',
    price: 32,
    budget: BudgetLevel.VALUE,
    emoji: '🥓',
    description: '灯盏窝不仅是肉的形状，更是它carry全场米饭的证明。',
  },
  {
    id: '43',
    name: '番茄炒蛋 (新秀红利)',
    price: 15,
    budget: BudgetLevel.POOR,
    emoji: '🍅',
    description: '简单易学，性价比极高，就像刚选中的乐透秀一样好用。',
  },
  {
    id: '44',
    name: '水煮肉片 (火爆主场)',
    price: 45,
    budget: BudgetLevel.RICH,
    emoji: '🔥',
    description: '红油滚滚，辣味十足，气氛火爆得就像季后赛的主场。',
  },
  {
    id: '45',
    name: '京酱肉丝 (精妙传切)',
    price: 28,
    budget: BudgetLevel.VALUE,
    emoji: '🌯',
    description: '豆腐皮卷肉丝葱丝，每一个卷都是一次精妙的传切配合。',
  },
  {
    id: '46',
    name: '松仁玉米 (三分射手)',
    price: 22,
    budget: BudgetLevel.VALUE,
    emoji: '🌽',
    description: '清甜爽口，粒粒分明，就像定点三分射手一样精准。',
  },
  {
    id: '47',
    name: '蒜苔炒肉 (稳健老将)',
    price: 20,
    budget: BudgetLevel.VALUE,
    emoji: '🎋',
    description: '不出错的选择，像队里的老将一样稳健，虽不华丽但管饱。',
  },
  {
    id: '48',
    name: '红烧排骨 (顶薪合同)',
    price: 58,
    budget: BudgetLevel.RICH,
    emoji: '🍖',
    description: '色泽红亮，味道浓郁，这道菜值得一份顶薪合同。',
  },
  {
    id: '49',
    name: '凉拌黄瓜 (更衣室领袖)',
    price: 10,
    budget: BudgetLevel.POOR,
    emoji: '🥒',
    description: '清脆爽口解油腻，能调节整桌菜的气氛，绝对的更衣室领袖。',
  },
  {
    id: '50',
    name: '扬州炒饭 (板凳匪徒)',
    price: 25,
    budget: BudgetLevel.VALUE,
    emoji: '🍚',
    description: '料足味美，哪怕作为替补出场（主食），也能拿高分。',
  },
  {
    id: '51',
    name: '可乐鸡翅 (快乐篮球)',
    price: 35,
    budget: BudgetLevel.VALUE,
    emoji: '🍗',
    description: '甜甜的快乐味道，吃完这顿，在这个联盟里打球就是为了开心。',
  },
  {
    id: '52',
    name: '干煸四季豆 (防守反击)',
    price: 22,
    budget: BudgetLevel.VALUE,
    emoji: '🌿',
    description: '外皮干香，口感独特，像一次犀利的防守反击快攻。',
  },
  {
    id: '53',
    name: '红烧茄子 (软手感)',
    price: 18,
    budget: BudgetLevel.POOR,
    emoji: '🍆',
    description: '软糯入味，就像顶级射手柔和的手感，怎么投怎么有。',
  },
  {
    id: '54',
    name: '糖醋里脊 (流量担当)',
    price: 36,
    budget: BudgetLevel.VALUE,
    emoji: '🥢',
    description: '酸酸甜甜，深受小朋友和大人喜爱，菜单里的流量担当。',
  },
  {
    id: '55',
    name: '毛血旺 (全攻全守)',
    price: 68,
    budget: BudgetLevel.RICH,
    emoji: '🌶️',
    description: '鸭血、毛肚、火腿...什么都有，全攻全守的豪华阵容。',
  },
  {
    id: '56',
    name: '酸辣土豆丝 (基本功)',
    price: 12,
    budget: BudgetLevel.POOR,
    emoji: '🥔',
    description: '考验刀工和火候，就像运球基本功，越简单的招式越难练。',
  },
  {
    id: '57',
    name: '葱爆羊肉 (爆发力)',
    price: 48,
    budget: BudgetLevel.RICH,
    emoji: '🐑',
    description: '大火爆炒，香气四溢，展现出惊人的第一步爆发力。',
  },
  {
    id: '58',
    name: '口水鸡 (垃圾话大王)',
    price: 38,
    budget: BudgetLevel.VALUE,
    emoji: '🐔',
    description: '麻辣鲜香让人流口水，就像垃圾话大王一样让人又爱又恨。',
  },
  {
    id: '59',
    name: '韭菜盒子 (边缘奇兵)',
    price: 15,
    budget: BudgetLevel.POOR,
    emoji: '🥟',
    description: '外酥里鲜，关键时刻替补上场能得奇效。',
  },
  {
    id: '60',
    name: '大盘鸡 (双塔战术)',
    price: 68,
    budget: BudgetLevel.RICH,
    emoji: '🍛',
    description: '鸡肉配土豆，还要加宽面，就像双塔战术一样统治禁区。',
  },
  {
    id: '61',
    name: '西红柿牛腩 (强力锋线)',
    price: 52,
    budget: BudgetLevel.RICH,
    emoji: '🥩',
    description: '酸甜开胃，牛肉软烂，像强力锋线一样能里能外。',
  },
  {
    id: '62',
    name: '炸酱面 (主场哨)',
    price: 18,
    budget: BudgetLevel.POOR,
    emoji: '🍜',
    description: '地道的老北京味儿，在主场吃这碗面，谁来都得输。',
  },
  {
    id: '63',
    name: '油焖大虾 (奢华三分)',
    price: 68,
    budget: BudgetLevel.RICH,
    emoji: '🦐',
    description: '色泽红润，味道鲜美，像库里的超远三分一样奢华。',
  },
  {
    id: '64',
    name: '清蒸鲈鱼 (养生曼巴)',
    price: 58,
    budget: BudgetLevel.RICH,
    emoji: '🐟',
    description: '清淡健康，保留原汁原味，适合职业生涯后期的养生打法。',
  },
  {
    id: '65',
    name: '蚂蚁上树 (灵活跑位)',
    price: 20,
    budget: BudgetLevel.POOR,
    emoji: '🥢',
    description: '肉末粘在粉丝上，就像球员灵活跑位，无处不在。',
  },
  {
    id: '66',
    name: '干锅花菜 (激情暂停)',
    price: 26,
    budget: BudgetLevel.VALUE,
    emoji: '🥦',
    description: '干香微辣，吃一口精神抖擞，像教练叫了个激情暂停。',
  },
  {
    id: '67',
    name: '辣子鸡 (高难度进球)',
    price: 42,
    budget: BudgetLevel.RICH,
    emoji: '🌶️',
    description: '在辣椒堆里找鸡肉，就像在严防死守下投进高难度进球。',
  },
  {
    id: '68',
    name: '疙瘩汤 (暖心队友)',
    price: 15,
    budget: BudgetLevel.POOR,
    emoji: '🥣',
    description: '热乎乎的，当你投篮不准时，它就是那个给你鼓励的暖心队友。',
  },
  {
    id: '69',
    name: '烤羊肉串 (街球风)',
    price: 6,
    budget: BudgetLevel.POOR,
    emoji: '🍢',
    description: '撸串喝酒，花哨的运球，这就是最纯粹的街球风格。',
  },
  {
    id: '70',
    name: '酸汤肥牛 (金黄战袍)',
    price: 48,
    budget: BudgetLevel.RICH,
    emoji: '🐮',
    description: '金黄的汤底，鲜嫩的肥牛，穿上这身战袍就是冠军有利争夺者。',
  },
  {
    id: '71',
    name: '鱼头泡饼 (绝代双骄)',
    price: 88,
    budget: BudgetLevel.RICH,
    emoji: '🥘',
    description: '鱼头和饼的结合，就像那一年的绝代双骄，缺一不可。',
  },
  {
    id: '72',
    name: '夫妻肺片 (黄金搭档)',
    price: 38,
    budget: BudgetLevel.VALUE,
    emoji: '🥗',
    description: '麻辣鲜香，配合默契，就像历史级别的黄金后场搭档。',
  },
  {
    id: '73',
    name: '木须肉 (万金油)',
    price: 24,
    budget: BudgetLevel.VALUE,
    emoji: '🥚',
    description: '肉、蛋、木耳、黄瓜，什么位置都能打，球队的万金油。',
  },
  {
    id: '74',
    name: '孜然羊肉 (西北野兽)',
    price: 46,
    budget: BudgetLevel.RICH,
    emoji: '🍖',
    description: '孜然的狂野香气，像来自西北的野兽派大前锋，无人能挡。',
  },
  {
    id: '75',
    name: '炒方便面 (加时赛)',
    price: 12,
    budget: BudgetLevel.POOR,
    emoji: '🍜',
    description: '深夜食堂的王者，当你打到加时赛体力不支时，它是最好的补给。',
  },
  {
    id: '76',
    name: '红糖糍粑 (甜点时刻)',
    price: 18,
    budget: BudgetLevel.POOR,
    emoji: '🍡',
    description: '外酥里软，甜蜜收尾，就像锁定胜局后的庆祝时刻。',
  },
  {
    id: '77',
    name: '铁锅炖大鹅 (总冠军)',
    price: 128,
    budget: BudgetLevel.RICH,
    emoji: '🦢',
    description: '分量巨大，排面十足，只有总冠军庆功宴才配得上的硬菜。',
  },
  {
    id: '78',
    name: '拍黄瓜 (开场哨)',
    price: 8,
    budget: BudgetLevel.POOR,
    emoji: '🥒',
    description: '清爽开胃，比赛开始前的热身，为整场盛宴拉开序幕。',
  }
];